version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4100:4100"
    environment:
      - CONTENT_APP_PORT=${CONTENT_APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONTENT_DB_NAME=${CONTENT_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_FOLDER_NAME=${STORAGE_FOLDER_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
      - STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - STORAGE_REGION=${STORAGE_REGION}
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minio123
    networks:
      - hidaya

networks:
  hidaya:
    name: hidaya
    external: true