version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4100:4100"
    environment:
      - APP_PORT=4100
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=secret
      - STORAGE_ENDPOINT=minio:9000
      - STORAGE_PUBLIC_URL=http://localhost:9000
      - STORAGE_ACCESS_KEY=iL6P5GSsdYofSMyt2Zd7
      - STORAGE_SECRET_KEY=GGcQA2Ndyu3FmPHiepPK4l2VQeG41QsWGE0vlRX0
      - STORAGE_BUCKET_NAME=hidaya
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minio123
    networks:
      - hidaya

networks:
  hidaya:
    name: hidaya
    external: true